### ISSUE TITLE
Private feeds have been scraped and are now public. How can we remove them?

### ISSUE THREAD

**Issue by agnul** [yinhm/friendfeed#3]
The subject says it all. Please give us a way to remove private data.

**Comment by yinhm** [comment]
I'm aware this issue, private issue should restore to private state shortly.

**Comment by yinhm** [comment]
Private feed restored to private state as of commit https://github.com/yinhm/friendfeed/commit/948d6c5082f064567d0755effeb44a2a48e5a14e
