### ISSUE TITLE
Documentation needs improvement

### ISSUE THREAD

**Issue by k0fi** [yinhm/friendfeed#7]
Hello,
I am very intersted to test this project but  the docs is not really helpful. I'm not familar with google cloud stuff and got stock there, despite the fact that I am quite competent linux user.
Could you please update the docs, so that one can test the project on a local Ubuntu machine?
I tried to clone the project into my machine but I get:

So I did:

`go get cloud.google.com/go/storage
`
And after this error:

```
package google.golang.org/cloud: code in directory /home/me/go/src/google.golang.org/cloud expects import "cloud.google.com/go"
package google.golang.org/cloud/storage: code in directory 
/home/me/go/src/google.golang.org/cloud/storage expects import "cloud.google.com/go/storage"
```
I imported your code:

`go get github.com/yinhm/friendfeed
`

But still get:

```
../github.com/yinhm/friendfeed/media/media.go:18:2: code in directory /home/me/go/src/google.golang.org/cloud expects import "cloud.google.com/go"
../github.com/yinhm/friendfeed/media/media.go:19:2: code in directory /home/me/go/src/google.golang.org/cloud/storage expects import "cloud.google.com/go/storage"

```

Appreciate your hints.

**Comment by yinhm** [comment]
This project has been updated to go1.6 which use mod by default, which should resolve the problem.
